In [10]:
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

In [ ]:
import pandas as pd
data = pd.read_csv('clear_data/overall_data.csv')

In [12]:
data

,headline_cpi,core_cpi,inf_expectation,gdp_change,year,quarter,potential_gdp,output_gap,unemployment
0,1.1,-4.1,1.5,5.7,1999,4,436612.737794,0.568069,5.8
1,0.8,3.7,2.3,4.9,2000,1,440240.419726,0.976644,5.8
2,0.6,-3.1,2.4,2.8,2000,2,443834.332802,0.899134,5.5
3,0.8,4.8,2.2,2.4,2000,3,447389.368326,0.737307,5.3
4,1.0,-3.1,2.3,2.4,2000,4,450902.911771,0.564221,5.2
...,...,...,...,...,...,...,...,...,...
92,10.7,0.0,4.8,1.2,2022,4,622687.300277,1.823821,3.9
93,10.2,14.3,3.9,0.4,2023,1,625410.985046,1.471195,4.0
94,8.4,5.2,3.5,0.0,2023,2,628133.288676,1.033333,4.2
95,6.7,3.8,3.6,-0.4,2023,3,630850.307630,0.492303,4.1
96,4.2,-0.9,3.3,-1.2,2023,4,633562.195063,-0.274195,3.8

In [13]:
inf_ex = data["inf_expectation"]
inf_ex

0     1.5
1     2.3
2     2.4
3     2.2
4     2.3
     ...
92    4.8
93    3.9
94    3.5
95    3.6
96    3.3
Name: inf_expectation, Length: 97, dtype: float64

In [14]:
data["int_ex_forecast"] = data["inf_expectation"].rolling(4).mean().shift(1)

In [15]:
data

,headline_cpi,core_cpi,inf_expectation,gdp_change,year,quarter,potential_gdp,output_gap,unemployment,int_ex_forecast
0,1.1,-4.1,1.5,5.7,1999,4,436612.737794,0.568069,5.8,NaN
1,0.8,3.7,2.3,4.9,2000,1,440240.419726,0.976644,5.8,NaN
2,0.6,-3.1,2.4,2.8,2000,2,443834.332802,0.899134,5.5,NaN
3,0.8,4.8,2.2,2.4,2000,3,447389.368326,0.737307,5.3,NaN
4,1.0,-3.1,2.3,2.4,2000,4,450902.911771,0.564221,5.2,2.100
...,...,...,...,...,...,...,...,...,...,...
92,10.7,0.0,4.8,1.2,2022,4,622687.300277,1.823821,3.9,4.250
93,10.2,14.3,3.9,0.4,2023,1,625410.985046,1.471195,4.0,4.650
94,8.4,5.2,3.5,0.0,2023,2,628133.288676,1.033333,4.2,4.550
95,6.7,3.8,3.6,-0.4,2023,3,630850.307630,0.492303,4.1,4.275
96,4.2,-0.9,3.3,-1.2,2023,4,633562.195063,-0.274195,3.8,3.950

In [16]:
data = data.dropna()

In [17]:
data

,headline_cpi,core_cpi,inf_expectation,gdp_change,year,quarter,potential_gdp,output_gap,unemployment,int_ex_forecast
4,1.0,-3.1,2.3,2.4,2000,4,450902.911771,0.564221,5.2,2.100
5,0.9,4.8,2.1,3.6,2001,1,454374.410251,0.727504,5.1,2.300
6,1.5,0.0,2.1,1.6,2001,2,457804.900937,0.396479,5.0,2.250
7,1.5,3.1,2.2,2.0,2001,3,461197.486996,0.177476,5.1,2.175
8,1.0,-1.0,1.9,1.2,2001,4,464556.406028,-0.248066,5.2,2.175
...,...,...,...,...,...,...,...,...,...,...
92,10.7,0.0,4.8,1.2,2022,4,622687.300277,1.823821,3.9,4.250
93,10.2,14.3,3.9,0.4,2023,1,625410.985046,1.471195,4.0,4.650
94,8.4,5.2,3.5,0.0,2023,2,628133.288676,1.033333,4.2,4.550
95,6.7,3.8,3.6,-0.4,2023,3,630850.307630,0.492303,4.1,4.275
96,4.2,-0.9,3.3,-1.2,2023,4,633562.195063,-0.274195,3.8,3.950